environments:
  - name: dev
    configs:
      endpoints:
          production:
              url: 'https://63.250.56.20:8443/STRSmartWWs/STRAWMAsync?wsdl'
          sandbox:
              url: 'https://63.250.56.20:8443/STRSmartWWs/STRAWMAsync?wsdl'
      deploymentEnvironments:
          - displayOnDevportal: true
            deploymentEnvironment: Default
            deploymentVhost : localhost
